[pytest]
markers =
    integration_test: marks tests as integration test (deselect with '-m "integration_test"')
    end2end_test: marks tests as end to end test (deselect with '-m "end2end_test"')
#addopts = -s 
#esta opcion es para que muestre los prints de los test y usar ipdb.set_trace()
